default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: landchecker

test:
  <<: *default
  database: landchecker_test

production:
  primary:
    <<: *default
    database: landchecker_production
  cache:
    <<: *default
    database: landchecker_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: landchecker_production
    migrations_paths: db/queue_migrate
